/*
  This file is generated by "https://drive.google.com/file/d/1iYOik6-nWXY7YByqHToWi4ziPltngjGt/view?usp=sharing"

  1. Make a copy of the above Google Colab file, follow the steps to train your model.
  2. Down load the generated model.h
  3. Replace this model.h file with the downloaded one.
*/
const unsigned char model[] __attribute__((aligned(4))) = {

};